---
title: "Agriculture Dataset Exploratory Analysis"
description: |
  Exploratory analysis of the crop production data source. 
author:
  - name: Aditi Gautam
    url: https://github.com/adgautam
date: "`r Sys.Date()`"
output: 
    radix::radix_article:
      toc: true
      toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	rows.print=5
)

options(tibble.max_extra_cols = 5, tibble.print_max = 5)

library(fs) # cross-platform file system operations
```

#Importing dataset

```{r}
agri <- read_csv(path("apy.csv"))
#library(DataExplorer)
```

#Exploring and summarizing the dataset

```{r layout="l-body-outset"}
agri
```

```{r}
glimpse(agri)
```

```{r}
library(skimr)

skim(agri)
```

#Production tonnes per hectare

```{r}
agri$Production_by_Area <- agri$Production/agri$Area
```

#Subsetting MSP crops

```{r}
msp_crops <- agri[ which(agri$Crop=='Paddy'| agri$Crop=='Wheat' | agri$Crop=='Maize'| agri$Crop=='Barley'| agri$Crop=='Ragi'| agri$Crop=='Gram'|	agri$Crop=='Arhar/Tur'| agri$Crop=='Moong(Green Gram)'| agri$Crop=='Urad'| agri$Crop=='Masoor'| agri$Crop=='Groundnut'| agri$Crop=='Rapeseed &Mustard'| agri$Crop=='Soyabean'| agri$Crop=='Sesamum'| agri$Crop=='Sunflower'| agri$Crop=='Niger seed'| agri$Crop=='Cotton'| agri$Crop=='Jute & mesta'| agri$Crop=='Jowar'| agri$Crop=='Bajra'| agri$Crop=='Sugarcane'), ]
```

#Subsetting Non-MSP crops

```{r}
non_msp_crops <- agri[ which(agri$Crop!='Sugarcane'& agri$Crop!='Wheat'& agri$Crop!='Paddy'&  agri$Crop!='Maize'& agri$Crop!='Barley'& agri$Crop!='Ragi'& agri$Crop!='Gram'&	agri$Crop!='Arhar/Tur'& agri$Crop!='Moong(Green Gram)'& agri$Crop!='Urad'& agri$Crop!='Groundnut'& agri$Crop!='Rapeseed &Mustard'& agri$Crop!='Soyabean'& agri$Crop!='Sesamum'& agri$Crop!='Sunflower'& agri$Crop!='Niger seed'& agri$Crop!='Cotton'& agri$Crop!='Jute & mesta'& agri$Crop!='Total foodgrain'& agri$Crop!='Pulses total'& agri$Crop!='Oilseeds total'& agri$Crop!='Jowar'& agri$Crop!='Bajra'& agri$Crop!='Masoor'), ]
non_msp_crops$Average_Production_by_Area = mean(non_msp_crops$Production_by_Area, na.rm=TRUE)
```

#Graphing average production tonnes per hectare

```{r}
#library(ggplot2)
ggplot() +
    geom_point(data = msp_crops, aes(x = Crop_Year, y = Production_by_Area), color = "blue") +
    geom_point(data = non_msp_crops, aes(x = Crop_Year, y = Production_by_Area), color = "red")
```

#Looking at averages by crop

```{r}
msp_crops_production <- group_by(msp_crops,Crop)
msp_crops_production <- summarise(msp_crops_production, Average_Production_by_Area = mean(Production_by_Area, na.rm=TRUE))
msp_crops_production <- ungroup(msp_crops_production)
msp_crops_production
#We find that sugarcane and jute are outliers in mean production_by_area.
```
```{r}
non_msp_crops_production <- group_by(non_msp_crops,Crop)
non_msp_crops_production <- summarise(non_msp_crops_production, Average_Production_by_Area = mean(Production_by_Area, na.rm=TRUE))
non_msp_crops_production <- ungroup(non_msp_crops_production)
non_msp_crops_production
```



