---
title: "Merging_All_Datasets"
author: "Aditi Gautam"
date: "12/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	rows.print=5
)

options(tibble.max_extra_cols = 5, tibble.print_max = 5)

library(fs) # cross-platform file system operations
library(tidyverse)
library(skimr)
library(sf)
library(viridis)
library(MASS)
library(effects)
library(ggplot2)
library(ggiraph)
```

Loading all datasets
```{r}
agri <- read_csv(path("01_Agriculture/Agridata_Cleaned_Corrected.csv"))
nfhs2015 <- read_csv(path("02_Nutrition/NFHS2015_Cleaned.csv"))
districts <- read_sf(path("03_Geodata/data/polbnda_ind.shp")) 
```

```{r}
districts <- districts %>% 
  rename(district = laa)
```


Production of ALL Crops - by district

```{r}
agri2014 <- agri[agri$Crop_Year == 2014 | agri$Crop_Year == 2013 | agri$Crop_Year == 2012| agri$Crop_Year == 2011| agri$Crop_Year == 2010,]

agri_all_bydistrict <- group_by(agri2014, district, Crop) %>%
  summarise(mean = scales::comma(mean(Production_by_Area, na.rm = TRUE), accuracy = 0.1)) %>%
  pivot_wider(
    names_from = Crop,
    values_from = mean
  )
agri_all_bydistrict <- agri_all_bydistrict %>% mutate_if(is.character,as.numeric)
```
Production of MSP vs Non-MSP Crops - by district

```{r}
agri2014$msp_nomsp <- ifelse(agri2014$msp==TRUE, "MSP", "Non_MSP")
agri_msp_bydistrict <- group_by(agri2014, district, msp_nomsp) %>%
  summarise(mean = scales::comma(mean(Production_by_Area, na.rm = TRUE), accuracy = 0.1)) %>%
  pivot_wider(
    names_from = msp_nomsp, 
    values_from = mean
  )
agri_msp_bydistrict <- agri_msp_bydistrict %>% mutate_if(is.character,as.numeric)

agri_msp_bydistrict$MSP <- replace(agri_msp_bydistrict$MSP, which(agri_msp_bydistrict$MSP > 15), NA)
```

```{r}
agri_district_updated <- read_csv(path("01_Agriculture/Agri_Name_Updated.csv"))
agri_district_updated <- agri_district_updated %>% 
  rename(district = District_Name)
agri_all_bydistrict <-  left_join(agri_all_bydistrict, agri_district_updated, by = "district")
agri_msp_bydistrict <- left_join(agri_msp_bydistrict, agri_district_updated, by = "district")
```

```{r}
agri_all_bydistrict <- agri_all_bydistrict %>% 
  mutate(district = 
  case_when(
   Name_Updated != "NA" ~  Name_Updated, TRUE ~ district)
  )

agri_msp_bydistrict <- agri_msp_bydistrict %>% 
 mutate(district = 
  case_when(
   Name_Updated != "NA" ~  Name_Updated, TRUE ~ district)
  )
```

```{r}
nutri_district_updated <- read_csv(path("02_Nutrition/Nutrition_district_updated.csv"))
nutri_district_updated <- nutri_district_updated %>% 
  rename(district = District_Name)

nfhs2015 <- left_join(nfhs2015, nutri_district_updated, by = "district")
```

```{r}
nfhs2015 <- nfhs2015 %>% 
  mutate(district = 
    case_when(
      Name_Updated != "NA" ~  Name_Updated, TRUE ~ district)
  )
```

```{r}
merged <- merge(agri_all_bydistrict, agri_msp_bydistrict, by.x = "district", by.y = "district")
merged <- left_join(merged, nfhs2015, by = "district")
merged <- left_join(districts, merged, by = "district") %>% st_as_sf() 
#merged <- distinct(merged, District_Name, .keep_all= TRUE)
```

Maps

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = stunting_range))+
  scale_fill_viridis_c(alpha = 0.75)+
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Stunting Across Districts",
    subtitle = "From Low to High",
    caption = "Source: NFHS, 2015",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/stunting_map.png")
```

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = uw_range))+
  scale_fill_viridis_c(alpha = 0.75)+
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Underweight Across Districts",
    subtitle = "From Low to High",
    caption = "Source: NFHS, 2015",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )
ggsave("04_Visualizations/uw_map.png")
```

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = wasting_range))+
  scale_fill_viridis_c(alpha = 0.75)+
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Wasting Across Districts",
    subtitle = "From Low to High",
    caption = "Source: NFHS, 2015",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/wasting_map.png")
```

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = MSP)) +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "MSP Yield Across Districts (2010-2014)",
    caption = "Source: Ministry of Agriculture, India",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/MSP_map.png")
```

```{r}
ggplot(data = merged) +
    geom_sf(aes(fill = Non_MSP)) +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Non-MSP Yield Across Districts (2010-2014)",
    caption = "Source: Ministry of Agriculture, India",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/Non_MSP_map.png")
```

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = Rice)) +
  scale_fill_viridis_c(option = "plasma") +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Rice Yield Across Districts (2010-2014)",
    caption = "Source: Ministry of Agriculture, India",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/Rice_map.png")
```

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = Wheat)) +
  scale_fill_viridis_c(option = "plasma") +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Wheat Yield Across Districts (2010-2014)",
    caption = "Source: Ministry of Agriculture, India",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/Wheat_map.png")
```

```{r}
ggplot(data = merged) +
  geom_sf(aes(fill = Sugarcane)) +
  scale_fill_viridis_c(option = "plasma") +
  xlab("Longitude") +
  ylab("Latitude") +
  labs(
    title = "Sugarcane Yield Across Districts (2010-2014)",
    caption = "Source: Ministry of Agriculture, India",
  ) + 
  theme_bw() +
  theme(
    panel.grid.major = ggplot2::element_line(
      color = gray(0.5), linetype = "dashed", size = 0.5
    ),
    panel.background = ggplot2::element_rect(fill = gray(0.75))
  )

ggsave("04_Visualizations/Sugarcane_map.png")
```

Interactive Maps

```{r}
#gg <- ggplot(data = merged) +
    #geom_sf_interactive(aes(geometry = mid,
      #size = stunting_range, tooltip = district, data_id = district),
      #show.legend = "point")
  #x <- girafe( ggobj = gg)
  #if( interactive() ) print(x)
```

Regressions

```{r}
regression_msp = polr(as.factor(stunting_range) ~ MSP, data = merged, Hess=TRUE) 
summary(regression_msp)
```

```{r}
ctable <- coef(summary(regression_msp))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable
```

```{r}
regression_non_msp = polr(as.factor(stunting_range) ~ Non_MSP, data = merged, Hess=TRUE) 
summary(regression_non_msp)
```

```{r}
ctable1 <- coef(summary(regression_non_msp))
p <- pnorm(abs(ctable1[, "t value"]), lower.tail = FALSE) * 2
ctable1 <- cbind(ctable1, "p value" = p)
ctable1
```

```{r}
regression_msp_controls = polr(as.factor(stunting_range) ~ MSP+x12_women_who_are_literate_percent, data = merged, Hess=TRUE) 
summary(regression_msp_controls)
```

```{r}
ctable2 <- coef(summary(regression_msp_controls))
p <- pnorm(abs(ctable2[, "t value"]), lower.tail = FALSE) * 2
ctable2 <- cbind(ctable2, "p value" = p)
ctable2
```

```{r}
regression_msp_controls2 = polr(as.factor(stunting_range) ~ MSP + rural_population_percapita + x13_men_who_are_literate_percent, data = merged, Hess=TRUE) 
summary(regression_msp_controls2)
```

```{r}
ctable3 <- coef(summary(regression_msp_controls2))
p <- pnorm(abs(ctable3[, "t value"]), lower.tail = FALSE) * 2
ctable3 <- cbind(ctable3, "p value" = p)
ctable3
```

```{r}
regression_msp_uw = polr(as.factor(uw_range) ~ MSP, data = merged, Hess=TRUE) 
summary(regression_msp_uw)
```

```{r}
ctable4 <- coef(summary(regression_msp_uw))
p <- pnorm(abs(ctable4[, "t value"]), lower.tail = FALSE) * 2
ctable4 <- cbind(ctable4, "p value" = p)
ctable4
```

```{r}
regression_msp_wasting = polr(as.factor(wasting_range) ~ MSP, data = merged, Hess=TRUE) 
summary(regression_msp_wasting)
```

```{r}
ctable5 <- coef(summary(regression_msp_wasting))
p <- pnorm(abs(ctable5[, "t value"]), lower.tail = FALSE) * 2
ctable5 <- cbind(ctable5, "p value" = p)
ctable5
```

```{r}
regression_non_msp_uw = polr(as.factor(uw_range) ~ Non_MSP, data = merged, Hess=TRUE) 
summary(regression_non_msp_uw)
```

```{r}
ctable6 <- coef(summary(regression_non_msp_uw))
p <- pnorm(abs(ctable6[, "t value"]), lower.tail = FALSE) * 2
ctable6 <- cbind(ctable6, "p value" = p)
ctable6
```

```{r}
regression_non_msp_wasting = polr(as.factor(wasting_range) ~ Non_MSP, data = merged, Hess=TRUE) 
summary(regression_non_msp_wasting)
```

```{r}
ctable7 <- coef(summary(regression_non_msp_wasting))
p <- pnorm(abs(ctable7[, "t value"]), lower.tail = FALSE) * 2
ctable7 <- cbind(ctable7, "p value" = p)
ctable7
```
