---
title: "Nutrition Dataset Exploratory Analysis -2015"
description: |
  Exploratory analysis of the NFHS survey data from 2015-16. 
author:
  - name: Aditi Gautam
    url: https://github.com/adgautam
date: "`r Sys.Date()`"
output: 
    radix::radix_article:
      toc: true
      toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	rows.print=5
)

options(tibble.max_extra_cols = 5, tibble.print_max = 5)

library(fs) # cross-platform file system operations
library(tidyverse)
library(skimr)
library(readxl)
library(janitor)
```

# Importing dataset

```{r}
nfhs2015 <- read_csv(path("NFHS_2015.csv"))
spec(nfhs2015)
```

```{r layout="l-body-outset"}
nfhs2015
```

```{r}
glimpse(nfhs2015)
```

```{r}
skim(nfhs2015)
```

Cleaning and standardizing variable names

```{r}
nfhs2015 <- clean_names(nfhs2015)
```

Recoding the values of columns: stunting_range_d, uw_range_d, wasting_range_d

Stunting
```{r}
nfhs2015["stunting_range_d"][nfhs2015["stunting_range_d"] == "Low (< 25%)"] <- "Low"
nfhs2015["stunting_range_d"][nfhs2015["stunting_range_d"] == "Medium (25% - 40%)"] <- "Medium"
nfhs2015["stunting_range_d"][nfhs2015["stunting_range_d"] == "High (> 40%)"] <- "High"
```

Underweight
```{r}
nfhs2015["uw_range_d"][nfhs2015["uw_range_d"] == "Low (< 20%)"] <- "Low"
nfhs2015["uw_range_d"][nfhs2015["uw_range_d"] == "Medium (20% - 40%)"] <- "Medium"
nfhs2015["uw_range_d"][nfhs2015["uw_range_d"] == "High (> 40%)"] <- "High"
```

Wasting
```{r}
nfhs2015["wasting_range_d"][nfhs2015["wasting_range_d"] == "Low (< 15%)"] <- "Low"
nfhs2015["wasting_range_d"][nfhs2015["wasting_range_d"] == "Medium (15% - 25%)"] <- "Medium"
nfhs2015["wasting_range_d"][nfhs2015["wasting_range_d"] == "High (> 25%)"] <- "High"
```

For now, we will be focussing on the three variables related to nutrition: Stunting, Underweight, Wasting

```{r}
keeps <- c("state","district","stunting_range_d","uw_range_d","wasting_range_d")
nfhs2015_subset = nfhs2015[keeps]
```

```{r}
nfhs2015_subset <- nfhs2015_subset %>% mutate(state = toupper(state))
nfhs2015_subset <- nfhs2015_subset %>% mutate(district = toupper(district))
```

Exporting the cleaned dataset

```{r}
write.csv(nfhs2015_subset, file = "NFHS2015_Cleaned.csv")
```

